apiVersion: v1
kind: Secret
metadata:
  name: test-secret1
data:
  DB_HOST: TWl0aHJhbg==
  DB_USER: QWRtaW4xMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo2
  labels:
    purpose: demonstrate-envars2
spec:
  containers:
    - name: envar-demo-container
      image: nginx
      ports:
      - containerPort: 8082
      envFrom:
      - secretRef:
          name: test-secret1